setwd("../data/HandOutsandData'18")
#install.packages("lme4")
require(lme4)
data<-read.table("SparrowSize.txt",header=TRUE)
str(data)
names(data)
head(data)
hist(data$Tarsus)
mean(data$Tarsus,na.rm=TRUE)
median(data$Tarsus,na.rm = TRUE)
par(mfrow =c(2,2))
hist(data$Tarsus, breaks = 3, col = "grey")
hist(data$Tarsus, breaks = 10, col = "grey")
hist(data$Tarsus, breaks = 30, col = "grey")
hist(data$Tarsus, breaks = 100, col = "grey")

#install.packages("modeest")
require(modeest)
mlv(data$Tarsus, na.rm = TRUE)

d2<-subset(data, data$Tarsus != "NA")
length(d2$Tarsus)
mlv(d2$Tarsus)
range(data$Tarsus,na.rm = TRUE)
range(d2$Tarsus,na.rm = TRUE)
var(data$Bill,na.rm = TRUE)
mean(data$Bill,na.rm = TRUE)
sd(data$Bill,na.rm = TRUE)

var(data$Mass,na.rm = TRUE)
mean(data$Mass,na.rm = TRUE)
sd(data$Mass,na.rm = TRUE)

var(data$Wing,na.rm = TRUE)
mean(data$Wing,na.rm = TRUE)
sd(na.omit(data$Wing))

scale(d2$Tarsus)

